### ISSUE TITLE
source code permission 

### ISSUE THREAD

**Issue by kabatz** [Ismailhachimi/Text-Classification#2]
Dear Mr. Ismail

i am wondering if its possible to have the source code of this model since i am working on a very similar university project and that would be so helpful 

best regards
Ghassan Rawshdeh

**Comment by Ismailhachimi** [comment]
Dear Ghassan,

I'm sorry for the very late response. I've been inactive for a while on Github. 

Please, feel free to use the project in any way you want.

Best regards,
Ismail E.
